# Generated by Django 3.2 on 2024-10-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razonsocial', models.CharField(max_length=70)),
                ('rutempresa', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('numerocasa', models.IntegerField()),
            ],
        ),
    ]
